#!/usr/bin/env python3
"""Proposed color-blocked palette (Docs/ColorLanguage.md) and its contrast check.

This is the single source for the proposal's hex values until they move into the asset
catalog. Run it to regenerate Docs/color-language-contrast.md:

    python3 Tools/color_language_check.py > Docs/color-language-contrast.md

It exits with an error if any pairing misses its target (WCAG 2.x relative luminance):
text 4.5:1, control outlines and state fills 3:1.
"""
import sys

PALETTE = {
    "Light": {
        "canvas": "#F4EEE6", "paper": "#FBF7F1", "well": "#F3EEE8",
        "text": "#29242A", "text2": "#5F5360", "neutralEdge": "#8C7F88",
        "roles": {
            "Rose (actions)": {"surface": "#EBD1D5", "edge": "#A5637A", "strong": "#633B55", "onStrong": "#FFFFFF", "ink": "#5A2E45"},
            "Powder (selectors)": {"surface": "#D3DFE6", "edge": "#5C7F95", "strong": "#2F5770", "onStrong": "#FFFFFF", "ink": "#23485E"},
            "Lavender (switches)": {"surface": "#DDD4E7", "edge": "#856FA3", "strong": "#5B4680", "onStrong": "#FFFFFF", "ink": "#443263"},
            "Butter (collapsible)": {"surface": "#F1E6C6", "edge": "#97803A", "strong": "#6F5A1E", "onStrong": "#FFFFFF", "ink": "#54431A"},
            "Sage (read-only)": {"surface": "#D6E0D1", "ink": "#2F4A35"},
        },
        "status": {
            "Positive": {"surface": "#E2EEDD", "ink": "#2F5E3C"},
            "Caution": {"surface": "#F7E3CF", "ink": "#8A4B12"},
            "Error": {"surface": "#F8E1E1", "ink": "#A12D39"},
            "Neutral": {"surface": "#EAE4DC", "ink": "#4F454C"},
        },
    },
    "Dark": {
        "canvas": "#1C191B", "paper": "#292529", "well": "#353035",
        "text": "#FAF7F2", "text2": "#C5B8C0", "neutralEdge": "#8F838B",
        "roles": {
            "Rose (actions)": {"surface": "#4A2F3A", "edge": "#B98A98", "strong": "#D9AFCB", "onStrong": "#1C191B", "ink": "#F3D9E0"},
            "Powder (selectors)": {"surface": "#2A3C47", "edge": "#7FA3B8", "strong": "#A9CBDD", "onStrong": "#14232B", "ink": "#D5E6EF"},
            "Lavender (switches)": {"surface": "#3A3149", "edge": "#A593C2", "strong": "#C9B8E6", "onStrong": "#221A30", "ink": "#E5DCF3"},
            "Butter (collapsible)": {"surface": "#453C22", "edge": "#B9A260", "strong": "#E2CF8E", "onStrong": "#2B2410", "ink": "#F3E8C2"},
            "Sage (read-only)": {"surface": "#2C3A2D", "ink": "#D3E3D0"},
        },
        "status": {
            "Positive": {"surface": "#273B2D", "ink": "#AFCEB6"},
            "Caution": {"surface": "#4A3320", "ink": "#F2C08D"},
            "Error": {"surface": "#4A2428", "ink": "#FFB3B8"},
            "Neutral": {"surface": "#3A353A", "ink": "#D8CDD4"},
        },
    },
}


def luminance(hex_value):
    h = hex_value.lstrip("#")
    channels = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    linear = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in channels]
    return 0.2126 * linear[0] + 0.7152 * linear[1] + 0.0722 * linear[2]


def ratio(a, b):
    la, lb = luminance(a), luminance(b)
    hi, lo = max(la, lb), min(la, lb)
    return (hi + 0.05) / (lo + 0.05)


failures = []


def row(mode, family, pairing, fg, bg, need):
    value = ratio(fg, bg)
    ok = value >= need
    if not ok:
        failures.append(f"{mode} {family} {pairing}: {value:.2f} < {need}")
    return f"| {family} | {pairing} | `{fg}` on `{bg}` | {value:.2f}:1 | {need}:1 | {'Pass' if ok else 'FAIL'} |"


print("# Color language contrast check")
print()
print("Generated by `Tools/color_language_check.py` from the proposed palette in "
      "[ColorLanguage.md](ColorLanguage.md). Text needs 4.5:1. Control outlines and "
      "selected or on fills need 3:1 against what surrounds them.")
for mode, p in PALETTE.items():
    print()
    print(f"## {mode}")
    print()
    print("| Family | Pairing | Colors | Ratio | Target | Result |")
    print("| --- | --- | --- | ---: | ---: | --- |")
    print(row(mode, "Neutrals", "Text on canvas", p["text"], p["canvas"], 4.5))
    print(row(mode, "Neutrals", "Text on paper", p["text"], p["paper"], 4.5))
    print(row(mode, "Neutrals", "Secondary text on canvas", p["text2"], p["canvas"], 4.5))
    print(row(mode, "Neutrals", "Secondary text on paper", p["text2"], p["paper"], 4.5))
    print(row(mode, "Neutrals", "Input outline on canvas", p["neutralEdge"], p["canvas"], 3.0))
    print(row(mode, "Neutrals", "Input outline on paper", p["neutralEdge"], p["paper"], 3.0))
    for family, f in p["roles"].items():
        print(row(mode, family, "Ink on surface", f["ink"], f["surface"], 4.5))
        print(row(mode, family, "Body text on surface", p["text"], f["surface"], 4.5))
        print(row(mode, family, "Secondary text on surface", p["text2"], f["surface"], 4.5))
        if "edge" in f:
            print(row(mode, family, "Outline on canvas", f["edge"], p["canvas"], 3.0))
            print(row(mode, family, "Outline on paper", f["edge"], p["paper"], 3.0))
            print(row(mode, family, "Outline on its own surface", f["edge"], f["surface"], 3.0))
            print(row(mode, family, "Label on strong fill", f["onStrong"], f["strong"], 4.5))
            print(row(mode, family, "Strong fill on canvas", f["strong"], p["canvas"], 3.0))
            print(row(mode, family, "Strong fill next to surface", f["strong"], f["surface"], 3.0))
    for family, f in p["status"].items():
        print(row(mode, f"Status: {family}", "Ink on surface", f["ink"], f["surface"], 4.5))

if failures:
    print("\n".join(failures), file=sys.stderr)
    sys.exit(1)
