#!/usr/bin/env python3
"""Prints the theme contrast table (WCAG 2.x) for the asset-catalog color tokens.
Usage: python3 Tools/contrast_check.py > Docs/contrast-table.md"""
import json, os

ROOT = os.path.join(os.path.dirname(__file__), "..", "LilyStyleMockup", "Resources", "Assets.xcassets")

def load(name):
    data = json.load(open(os.path.join(ROOT, f"{name}.colorset", "Contents.json")))
    vals = {}
    for c in data["colors"]:
        comp = c["color"]["components"]
        hexv = "".join(comp[k][2:] for k in ("red", "green", "blue"))
        vals["dark" if c.get("appearances") else "light"] = hexv
    return vals

def lum(h):
    r, g, b = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    f = lambda c: c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    return 0.2126 * f(r) + 0.7152 * f(g) + 0.0722 * f(b)

def ratio(a, b):
    la, lb = sorted([lum(a), lum(b)], reverse=True)
    return (la + 0.05) / (lb + 0.05)

PAIRS = [("PrimaryText", "Background", "text"), ("PrimaryText", "Surface", "text"), ("SecondaryText", "Background", "text"),
         ("SecondaryText", "Surface", "text"), ("SecondaryText", "AccentSurface", "text"), ("SecondaryText", "ImageWell", "text"),
         ("PrimaryText", "AccentSurface", "text"), ("PrimaryText", "SuccessSurface", "text"), ("PrimaryAction", "Background", "text/icon"),
         ("PrimaryAction", "Surface", "text/icon"), ("PrimaryAction", "AccentSurface", "selected chip text"),
         ("OnPrimaryAction", "PrimaryAction", "button label"), ("Success", "SuccessSurface", "badge text"), ("Success", "Surface", "text"),
         ("Error", "Background", "text"), ("Error", "Surface", "text"), ("ControlBorder", "Surface", "control outline (≥3:1)"),
         ("ControlBorder", "Background", "control outline (≥3:1)"), ("ControlBorder", "ImageWell", "control outline (≥3:1)"),
         ("Divider", "Surface", "decorative only"), ("Divider", "Background", "decorative only")]

print("# Theme contrast check\n")
print("Generated by `Tools/contrast_check.py` from the asset-catalog values (WCAG 2.x relative luminance). "
      "Normal text needs 4.5:1; large text and meaningful outlines/icons need 3:1.\n")
print("| Foreground | Background | Use | Light | Dark | Result |")
print("| --- | --- | --- | ---: | ---: | --- |")
for fg, bg, use in PAIRS:
    f, b = load(fg), load(bg)
    l, d = ratio(f["light"], b["light"]), ratio(f["dark"], b["dark"])
    need = 3.0 if "outline" in use else (0 if "decorative" in use else 4.5)
    res = "Decorative — never the only boundary" if need == 0 else ("Pass" if min(l, d) >= need else "FAIL")
    print(f"| {fg} | {bg} | {use} | {l:.2f}:1 | {d:.2f}:1 | {res} |")
